"""
Django settings for mimir project.

Generated by 'django-admin startproject' using Django 2.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import django

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
# BASE_DIR = '/Users/abclab/Desktop/tsai/Tsai team data'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'pi&hejn$l%r*ejvvee)@=ph!lgt&y+$=ec_2_npx6m-f*@np$8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1','140.112.16.129']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'social_django',

    'djangobower',
    'front_end',
    'api',
    'utils'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mimir.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'front_end', 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'mimir.wsgi.application'


# MongoClient
MONGO_HOST = 'localhost'
MONGO_PORT = 27017
# MONGO_USER = 'mimir'
#MONGO_PASSWORD = ''
# MONGO_NAME = 'mimir'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'zh-hant'
TIME_ZONE = 'Asia/Taipei'
USE_I18N = True
USE_L10N = True
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

# LOGIN_URL = 'login'

LOGIN_REDIRECT_URL = '/mimir/me'

# Social-Auth Setting
AUTHENTICATION_BACKENDS = (
 'social_core.backends.open_id.OpenIdAuth',
 'social_core.backends.google.GoogleOpenId',
 'social_core.backends.google.GoogleOAuth2',
 'django.contrib.auth.backends.ModelBackend',
)

# django-bower Setting
STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "djangobower.finders.BowerFinder",
) 

PROJECT_ROOT = os.path.abspath(
    os.path.join(os.path.dirname(__file__), ".."),
)

BOWER_COMPONENTS_ROOT = os.path.join(PROJECT_ROOT, 'front_end/static/front_end/')

BOWER_INSTALLED_APPS = (
    "bootstrap-slider#*",
    "chart.js#1.0.*",
    "ckeditor#^4.7.0",
    "bootstrap-colorpicker#^2.5.1",
    "bootstrap#^3.3.7",
    "jquery#3.2.1",
    "datatables.net#^1.10.15",
    "datatables.net-bs#^2.1.1",
    "bootstrap-datepicker#^1.7.0",
    "bootstrap-daterangepicker#^2.1.25",
    "moment#^2.18.1",
    "fastclick#^1.0.6",
    "flot#^0.8.3",
    "fullcalendar#^3.4.0",
    "jquery.inputmask#^3.3.7",
    "ionrangeslider#^2.2.0",
    "jvectormap#^2.0.4",
    "jquery-knob#^1.2.13",
    "morris.js#^0.5.1",
    "pace#^1.0.2",
    "select2#^4.0.3",
    "slimscroll#^1.3.8",
    "bootstrap-timepicker#^0.5.2",
    "jquery-sparkline#^2.1.3",
    "font-awesome#^4.7.0",
    "ionicons#^2.0.1",
    "jquery-ui#1.11.4"
)


# Google-OAuth2 Key & Secret (bigmoumou)
# If you need this feature, please connect bigmoumou
# SOCIAL_AUTH_GOOGLE_OAUTH2_KEY =''
# SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = ''
# SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = ['email']
# SOCIAL_AUTH_GOOGLE_PROFILE_EXTRA_PARAMS = {
#     'fields': 'id, name, email'
# }
